// multilingual.js
const translations = {
  en: {
    // Common UI texts for all pages
    languageEnglish: "English",
    languageHindi: "हिंदी",
    languageTamil: "தமிழ்",

    // Login Page
    mainTitle: "FoodChain Connect",
    mainDescription: "Connecting Street Food Vendors, Raw Material Suppliers & Transport Services",
    tabStreetVendor: "Street Food Vendor",
    tabRawMaterial: "Raw Material Vendor",
    tabTransport: "Transport Service",
    streetVendorLoginTitle: "Street Food Vendor Login",
    svUsernamePlaceholder: "Username or Email",
    svPasswordPlaceholder: "Password",
    svLoginBtn: "Login as Vendor",
    forgotPassword: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    register: "Register",
    rawMaterialLoginTitle: "Raw Material Supplier Login",
    rmUsernamePlaceholder: "Username or Email",
    rmPasswordPlaceholder: "Password",
    rmLoginBtn: "Login as Supplier",
    transportLoginTitle: "Transport Service Login",
    tsUsernamePlaceholder: "Username or Email",
    tsPasswordPlaceholder: "Password",
    tsLoginBtn: "Login as Transport",

    // Raw Material Dashboard
    navbarBrandRawMaterial: "Raw Material Supplier Dashboard",
    logoutBtnRawMaterial: "Logout",
    slide1TitleRawMaterial: "Supply Quality Raw Materials",
    slide1DescRawMaterial: "Connect with street food vendors and grow your business",
    slide2TitleRawMaterial: "Manage Your Inventory",
    slide2DescRawMaterial: "Keep track of your stock and orders efficiently",
    slide3TitleRawMaterial: "Track Your Deliveries",
    slide3DescRawMaterial: "Monitor order status and delivery progress",
    totalOrders: "Total Orders",
    totalRevenue: "Total Revenue",
    totalProducts: "Products Listed",
    totalCustomers: "Active Customers",
    orderMgmtTitle: "Order Management",
    orderStatusAll: "All Orders",
    orderStatusPending: "Pending",
    orderStatusProcessing: "Processing",
    orderStatusShipped: "Shipped",
    orderStatusDelivered: "Delivered",
    addProductBtn: "Add Product",
    productNameLabel: "Product Name",
    productNamePlaceholder: "Enter product name",
    categoryLabel: "Category",
    categoryVegetables: "Vegetables",
    categorySpices: "Spices",
    categoryGrains: "Grains",
    categoryDairy: "Dairy",
    categoryMeat: "Meat",
    pricePerKgLabel: "Price per kg (₹)",
    stockQuantityLabel: "Stock Quantity (kg)",
    descriptionLabel: "Description",
    productImageLabel: "Product Image URL",
    cancelAddProductBtn: "Cancel",
    saveProductBtn: "Save Product",
    orderDetailsTitle: "Order Details",
    closeOrderDetailsBtn: "Close",
    updateOrderStatusBtn: "Update Status",
    deliveryTrackingTitle: "Delivery Tracking",
    inventoryAlertsTitle: "Inventory Alerts",
    revenueOverviewTitle: "Revenue Overview",
    recentReviewsTitle: "Recent Reviews",

    // Street Vendor Dashboard
    navbarBrandStreetVendor: "Street Vendor Dashboard",
    slide1TitleStreet: "Fresh Ingredients for Your Street Food Business",
    slide1DescStreet: "Connect with reliable suppliers in your area",
    slide2TitleStreet: "Quality Raw Materials",
    slide2DescStreet: "Source the best ingredients for your customers",
    slide3TitleStreet: "Reliable Transport Services",
    slide3DescStreet: "Get your supplies delivered on time",
    serviceRangeTitle: "Select Your Service Range",
    searchLocationLabel: "Search Location",
    searchLocationPlaceholder: "Enter your location",
    serviceRangeLabel: "Service Range (km)",
    saveRangeBtn: "Save Range",
    rawMaterialsTitleStreet: "Raw Materials",
    filterBtnStreet: "Filters",
    allCategoriesOption: "All Categories",
    vegetablesOption: "Vegetables",
    spicesOption: "Spices",
    grainsOption: "Grains",
    dairyOption: "Dairy",
    meatOption: "Meat",
    searchProductsPlaceholder: "Search products...",
    cartTitle: "Cart",
    emptyCartText: "Your cart is empty",
    totalLabel: "Total:",
    checkoutBtn: "Checkout",
    collaborationTitle: "Wholesale Collaboration",
    collaborationText: "Join with other vendors for bulk orders and better prices!",
    joinCollaborationBtn: "Find Collaboration",
    orderTrackingTitle: "Order Tracking",
    noOrdersText: "No active orders",
    checkoutModalTitle: "Checkout",
    paymentMethodTitle: "Payment Method",
    payNowLabel: "Pay Now",
    buyNowPayLaterLabel: "Buy Now, Pay Later (Regular Customers Only)",
    transportServiceTitle: "Transport Service",
    needTransportLabel: "I need transport service",
    selectTransportOption: "Select Transport Service",
    cancelOrderBtn: "Cancel",
    confirmOrderBtn: "Confirm Order",

    // Transport Dashboard
    navbarBrandTransport: "Transport Service Dashboard",
    slide1TitleTransport: "Reliable Transport Services",
    slide1DescTransport: "Connect vendors with efficient delivery solutions",
    slide2TitleTransport: "Real-time Tracking",
    slide2DescTransport: "Monitor your deliveries with live GPS tracking",
    slide3TitleTransport: "Fast & Secure Delivery",
    slide3DescTransport: "Ensure timely and safe delivery of goods",
    totalDeliveriesLabel: "Total Deliveries",
    totalEarningsLabel: "Total Earnings",
    activeRoutesLabel: "Active Routes",
    averageRatingLabel: "Average Rating",
    deliveryRequestsTitle: "Delivery Requests",
    requestStatusAll: "All Requests",
    requestStatusPending: "Pending",
    requestStatusAccepted: "Accepted",
    requestStatusInTransit: "In Transit",
    requestStatusDelivered: "Delivered",
    refreshMapBtn: "Refresh",
    logoutBtnTransport: "Logout",
    requestDetailsTitle: "Delivery Request Details",
    closeRequestDetailsBtn: "Close",
    rejectRequestBtn: "Reject",
    acceptRequestBtn: "Accept Request",
    vehicleInfoTitle: "Update Vehicle Information",
    cancelVehicleInfoBtn: "Cancel",
    saveVehicleInfoBtn: "Save Information",
    vehicleTypeLabel: "Vehicle Type",
    selectTypeOption: "Select Type",
    vehicleTypeBike: "Bike",
    vehicleTypeAutoRickshaw: "Auto Rickshaw",
    vehicleTypeVan: "Van",
    vehicleTypeTruck: "Truck",
    vehicleNumberLabel: "Vehicle Number",
    vehicleNumberPlaceholder: "Enter vehicle number",
    capacityLabel: "Capacity (kg)",
    capacityPlaceholder: "Enter capacity",
    ratePerKmLabel: "Rate per km (₹)",
    ratePerKmPlaceholder: "Enter rate per km",
    serviceAreasLabel: "Service Areas",
    serviceAreasPlaceholder: "Enter areas you serve (comma separated)"
  },
  hi: {
    // Hindi translations for all keys
    languageEnglish: "अंग्रेज़ी",
    languageHindi: "हिंदी",
    languageTamil: "तामिल",

    mainTitle: "फूडचेन कनेक्ट",
    mainDescription: "सड़क भोजन विक्रेता, कच्चे माल आपूर्तिकर्ता और परिवहन सेवाओं को जोड़ना",
    tabStreetVendor: "सड़क भोजन विक्रेता",
    tabRawMaterial: "कच्चे माल विक्रेता",
    tabTransport: "परिवहन सेवा",
    streetVendorLoginTitle: "सड़क भोजन विक्रेता लॉगिन",
    svUsernamePlaceholder: "उपयोगकर्ता नाम या ईमेल",
    svPasswordPlaceholder: "पासवर्ड",
    svLoginBtn: "विक्रेता के रूप में लॉग इन करें",
    forgotPassword: "पासवर्ड भूल गए?",
    dontHaveAccount: "खाता नहीं है?",
    register: "रजिस्टर करें",
    rawMaterialLoginTitle: "कच्चे माल आपूर्तिकर्ता लॉगिन",
    rmUsernamePlaceholder: "उपयोगकर्ता नाम या ईमेल",
    rmPasswordPlaceholder: "पासवर्ड",
    rmLoginBtn: "आपूर्ताकर्ता के रूप में लॉग इन करें",
    transportLoginTitle: "परिवहन सेवा लॉगिन",
    tsUsernamePlaceholder: "उपयोगकर्ता नाम या ईमेल",
    tsPasswordPlaceholder: "पासवर्ड",
    tsLoginBtn: "परिवहन के रूप में लॉग इन करें",

    navbarBrandRawMaterial: "कच्चे माल आपूर्तिकर्ता डैशबोर्ड",
    logoutBtnRawMaterial: "लॉग आउट",
    slide1TitleRawMaterial: "गुणवत्ता कच्चा माल सप्लाई करें",
    slide1DescRawMaterial: "सड़क भोजन विक्रेताओं से जुड़ें और अपना व्यवसाय बढ़ाएं",
    slide2TitleRawMaterial: "अपने इन्वेंट्री का प्रबंधन करें",
    slide2DescRawMaterial: "अपने स्टॉक और ऑर्डर्स को कुशलता से ट्रैक करें",
    slide3TitleRawMaterial: "अपनी डिलीवरी ट्रैक करें",
    slide3DescRawMaterial: "ऑर्डर स्थिति और डिलीवरी प्रगति पर नज़र रखें",
    totalOrders: "कुल ऑर्डर",
    totalRevenue: "कुल राजस्व",
    totalProducts: "लिस्टेड उत्पाद",
    totalCustomers: "सक्रिय ग्राहक",
    orderMgmtTitle: "ऑर्डर प्रबंधन",
    orderStatusAll: "सभी ऑर्डर",
    orderStatusPending: "लंबित",
    orderStatusProcessing: "प्रोसेसिंग",
    orderStatusShipped: "शिप्ड",
    orderStatusDelivered: "डिलीवर किया गया",
    addProductBtn: "उत्पाद जोड़ें",
    productNameLabel: "उत्पाद का नाम",
    productNamePlaceholder: "उत्पाद का नाम दर्ज करें",
    categoryLabel: "श्रेणी",
    categoryVegetables: "सब्ज़ियाँ",
    categorySpices: "मसाले",
    categoryGrains: "अनाज",
    categoryDairy: "डेयरी",
    categoryMeat: "मांस",
    pricePerKgLabel: "प्रति किलोग्राम मूल्य (₹)",
    stockQuantityLabel: "स्टॉक मात्रा (किलो)",
    descriptionLabel: "विवरण",
    productImageLabel: "उत्पाद छवि URL",
    cancelAddProductBtn: "रद्द करें",
    saveProductBtn: "उत्पाद सहेजें",
    orderDetailsTitle: "ऑर्डर विवरण",
    closeOrderDetailsBtn: "बंद करें",
    updateOrderStatusBtn: "स्थिति अपडेट करें",
    deliveryTrackingTitle: "डिलीवरी ट्रैकिंग",
    inventoryAlertsTitle: "इन्वेंट्री चेतावनी",
    revenueOverviewTitle: "राजस्व अवलोकन",
    recentReviewsTitle: "हाल की समीक्षाएं",

    navbarBrandStreetVendor: "सड़क विक्रेता डैशबोर्ड",
    slide1TitleStreet: "आपके सड़क भोजन व्यवसाय के लिए ताजगी से भरपूर सामग्री",
    slide1DescStreet: "अपने इलाके के भरोसेमंद आपूर्तिकर्ताओं से जुड़ें",
    slide2TitleStreet: "गुणवत्ता कच्चा माल",
    slide2DescStreet: "अपने ग्राहकों के लिए श्रेष्ठ सामग्री का स्रोत",
    slide3TitleStreet: "विश्वसनीय परिवहन सेवाएं",
    slide3DescStreet: "अपनी आपूर्ति समय पर प्राप्त करें",
    serviceRangeTitle: "अपनी सेवा सीमा चुनें",
    searchLocationLabel: "स्थान खोजें",
    searchLocationPlaceholder: "अपना स्थान दर्ज करें",
    serviceRangeLabel: "सेवा सीमा (कि.मी.)",
    saveRangeBtn: "सीमा सहेजें",
    rawMaterialsTitleStreet: "कच्चा माल",
    filterBtnStreet: "फ़िल्टर",
    allCategoriesOption: "सभी श्रेणियाँ",
    vegetablesOption: "सब्ज़ियाँ",
    spicesOption: "मसाले",
    grainsOption: "अनाज",
    dairyOption: "डेयरी",
    meatOption: "मांस",
    searchProductsPlaceholder: "उत्पाद खोजें...",
    cartTitle: "कार्ट",
    emptyCartText: "आपका कार्ट खाली है",
    totalLabel: "कुल:",
    checkoutBtn: "चेकआउट",
    collaborationTitle: "थोक सहयोग",
    collaborationText: "थोक आदेशों और बेहतर कीमतों के लिए अन्य विक्रेताओं के साथ जुड़ें!",
    joinCollaborationBtn: "सहयोग खोजें",
    orderTrackingTitle: "ऑर्डर ट्रैकिंग",
    noOrdersText: "कोई सक्रिय ऑर्डर नहीं",
    checkoutModalTitle: "चेकआउट",
    paymentMethodTitle: "भुगतान विधि",
    payNowLabel: "अभी भुगतान करें",
    buyNowPayLaterLabel: "अभी खरीदें, बाद में भुगतान करें (नियमित ग्राहक)",
    transportServiceTitle: "परिवहन सेवा",
    needTransportLabel: "मुझे परिवहन सेवा चाहिए",
    selectTransportOption: "परिवहन सेवा चुनें",
    cancelOrderBtn: "रद्द करें",
    confirmOrderBtn: "ऑर्डर पुष्टि करें",

    navbarBrandTransport: "परिवहन सेवा डैशबोर्ड",
    slide1TitleTransport: "विश्वसनीय परिवहन सेवाएं",
    slide1DescTransport: "विक्रेताओं को कुशल डिलीवरी समाधान के साथ जोड़ें",
    slide2TitleTransport: "रीयल-टाइम ट्रैकिंग",
    slide2DescTransport: "लाइव GPS ट्रैकिंग के साथ अपनी डिलीवरी की निगरानी करें",
    slide3TitleTransport: "तेज और सुरक्षित डिलीवरी",
    slide3DescTransport: "सामान की समय पर और सुरक्षित डिलीवरी सुनिश्चित करें",
    totalDeliveriesLabel: "कुल डिलीवरी",
    totalEarningsLabel: "कुल कमाई",
    activeRoutesLabel: "सक्रिय मार्ग",
    averageRatingLabel: "औसत रेटिंग",
    deliveryRequestsTitle: "डिलीवरी अनुरोध",
    requestStatusAll: "सभी अनुरोध",
    requestStatusPending: "लंबित",
    requestStatusAccepted: "स्वीकार किया गया",
    requestStatusInTransit: "ट्रांजिट में",
    requestStatusDelivered: "डिलीवर किया गया",
    refreshMapBtn: "रिफ्रेश",
    logoutBtnTransport: "लॉग आउट",
    requestDetailsTitle: "डिलीवरी अनुरोध विवरण",
    closeRequestDetailsBtn: "बंद करें",
    rejectRequestBtn: "अस्वीकार करें",
    acceptRequestBtn: "अनुरोध स्वीकार करें",
    vehicleInfoTitle: "वाहन जानकारी अपडेट करें",
    cancelVehicleInfoBtn: "रद्द करें",
    saveVehicleInfoBtn: "जानकारी सहेजें",
    vehicleTypeLabel: "वाहन का प्रकार",
    selectTypeOption: "प्रकार चुनें",
    vehicleTypeBike: "बाइक",
    vehicleTypeAutoRickshaw: "ऑटो रिक्शा",
    vehicleTypeVan: "वैन",
    vehicleTypeTruck: "ट्रक",
    vehicleNumberLabel: "वाहन संख्या",
    placeholderVehicleNumber: "वाहन संख्या दर्ज करें",
    capacityLabel: "क्षमता (कि.ग्रा.)",
    placeholderCapacity: "क्षमता दर्ज करें",
    ratePerKmLabel: "प्रति किलोमीटर दर (₹)",
    placeholderRatePerKm: "प्रति किलोमीटर दर दर्ज करें",
    serviceAreasLabel: "सेवा क्षेत्र",
    placeholderServiceAreas: "आप जिन क्षेत्रों में सेवा देते हैं उन्हें दर्ज करें (कॉमा से अलग करें)"
  },
  ta: {
    // Tamil translations go here (same keys as English/Hindi)
    languageEnglish: "ஆங்கிலம்",
    languageHindi: "ஹிந்தி",
    languageTamil: "தமிழ்",

    mainTitle: "பூட்‌ச்சேன் கனெக்ட்",
    mainDescription: "தெரு உணவு விற்பனையாளர்கள், மூலப்பொருள் வழங்கியாளர்கள் மற்றும் போக்குவரத்து சேவைகளை இணைத்தல்",
    tabStreetVendor: "தெரு உணவு விற்பனையாளர்",
    tabRawMaterial: "மூலப்பொருள் வழங்கியாளர்",
    tabTransport: "போக்குவரத்து சேவை",
    streetVendorLoginTitle: "தெரு உணவு விற்பனையாளர் உள்நுழைவு",
    svUsernamePlaceholder: "பயனர்பெயர் அல்லது மின்னஞ்சல்",
    svPasswordPlaceholder: "கடவுச்சொல்",
    svLoginBtn: "விற்பனையாளராக உள்நுழைக",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    register: "பதிவு செய்யவும்",
    rawMaterialLoginTitle: "மூலப்பொருள் வழங்கியாளர் உள்நுழைவு",
    rmUsernamePlaceholder: "பயனர்பெயர் அல்லது மின்னஞ்சல்",
    rmPasswordPlaceholder: "கடவுச்சொல்",
    rmLoginBtn: "வழங்கியாளராக உள்நுழைக",
    transportLoginTitle: "போக்குவரத்து சேவை உள்நுழைவு",
    tsUsernamePlaceholder: "பயனர்பெயர் அல்லது மின்னஞ்சல்",
    tsPasswordPlaceholder: "கடவுச்சொல்",
    tsLoginBtn: "போக்குவரத்தராக உள்நுழைக",

    navbarBrandRawMaterial: "மூலப்பொருள் வழங்கியாளர் டாஷ்போர்ட்",
    logoutBtnRawMaterial: "வெளியேறு",
    slide1TitleRawMaterial: "தெளிவான தரமான மூலப் பொருட்கள் வழங்குங்கள்",
    slide1DescRawMaterial: "தெரு உணவு விற்பனையாளர்களுடன் இணைந்து உங்கள் வணிகத்தை விரிவாக்குங்கள்",
    slide2TitleRawMaterial: "உங்கள் சேமிப்புகளை நிர்வகிக்கவும்",
    slide2DescRawMaterial: "உங்கள் பங்கு மற்றும் ஆர்டர்களை திறமையாக கண்காணியுங்கள்",
    slide3TitleRawMaterial: "உங்கள் விநியோகங்களை கவனியுங்கள்",
    slide3DescRawMaterial: "ஆர்டர் நிலை மற்றும் விநியோக முன்னேற்றத்தை கண்காணியுங்கள்",
    totalOrders: "மொத்த ஆர்டர்கள்",
    totalRevenue: "மொத்த வருவாய்",
    totalProducts: "பொருட்கள் பட்டியல்",
    totalCustomers: "செயல்பாட்டில் உள்ள வாடிக்கையாளர்கள்",
    orderMgmtTitle: "ஆர்டர் மேலாண்மை",
    orderStatusAll: "அனைத்து ஆர்டர்களும்",
    orderStatusPending: "காத்திருக்கிறது",
    orderStatusProcessing: "செயற்படும் நிலையில்",
    orderStatusShipped: "அனுப்பப்பட்டது",
    orderStatusDelivered: "விளம்பப்பட்டது",
    addProductBtn: "பொருள் சேர்க்கவும்",
    productNameLabel: "பொருள் பெயர்",
    productNamePlaceholder: "பொருள் பெயரை உள்ளிடவும்",
    categoryLabel: "வகை",
    categoryVegetables: "காய்கறிகள்",
    categorySpices: "மசாலா",
    categoryGrains: "தானியம்",
    categoryDairy: "பால் தயாரிப்புகள்",
    categoryMeat: "இறைச்சி",
    pricePerKgLabel: "கிலோக்கு விலை (₹)",
    stockQuantityLabel: "சேமிப்புத் தொகை (கிலோ)",
    descriptionLabel: "விவரம்",
    productImageLabel: "பொருள் படம் URL",
    cancelAddProductBtn: "ரத்து செய்",
    saveProductBtn: "பொருள் சேமி",
    orderDetailsTitle: "ஆர்டர் விவரங்கள்",
    closeOrderDetailsBtn: "மூடு",
    updateOrderStatusBtn: "நிலை புதுப்பி",
    deliveryTrackingTitle: "விநியோக கண்காணிப்பு",
    inventoryAlertsTitle: "சேமிப்பு எச்சரிக்கை",
    revenueOverviewTitle: "வருவாய் கண்ணோட்டம்",
    recentReviewsTitle: "சமீபத்திய விமர்சனங்கள்",

    navbarBrandStreetVendor: "தெரு விற்பனையாளர் டாஷ்போர்ட்",
    slide1TitleStreet: "உங்கள் தெரு உணவுத் தொழிலுக்கான புதிய பொருட்கள்",
    slide1DescStreet: "உங்கள் பகுதிக்கு நம்பகமான வழங்குநர்களுடன் இணைக",
    slide2TitleStreet: "தரமான மூலப்பொருட்கள்",
    slide2DescStreet: "உங்கள் வாடிக்கையாளர் க்காக சிறந்த பொருட்களை வாங்குங்கள்",
    slide3TitleStreet: "நம்பகமான போக்குவரத்து சேவைகள்",
    slide3DescStreet: "உங்கள் பொருட்களை நேரத்துக்கு ஏற்ப எடுத்துக்கொள்ளுங்கள்",
    serviceRangeTitle: "உங்கள் சேவை வரம்பைத் தெரிவு செய்க",
    searchLocationLabel: "இடத்தைத் தேடு",
    searchLocationPlaceholder: "உங்கள் இடத்தை உள்ளிடவும்",
    serviceRangeLabel: "சேவை வரம்பு (கிமீ)",
    saveRangeBtn: "வரம்பை சேமி",
    rawMaterialsTitleStreet: "மூலப்பொருட்கள்",
    filterBtnStreet: "வடிகட்டிகள்",
    allCategoriesOption: "அனைத்து வகைகளும்",
    vegetablesOption: "காய்கறிகள்",
    spicesOption: "மசாலா",
    grainsOption: "தானியங்கள்",
    dairyOption: "பால்வேதிப்பொருட்கள்",
    meatOption: "இறைச்சி",
    searchProductsPlaceholder: "பொருட்களைத் தேடு...",
    cartTitle: "கார்ட்",
    emptyCartText: "உங்கள் கார்ட் காலியாக உள்ளது",
    totalLabel: "மொத்தம்:",
    checkoutBtn: "செக் அவுட்",
    collaborationTitle: "தொகுதி ஒத்துழைப்பு",
    collaborationText: "பெரும்புள்ளி ஆர்டர்களுக்காக மற்ற விற்பனையாளர்களுடன் இணைக்கு!",
    joinCollaborationBtn: "ஒத்துழைப்பு காண்க",
    orderTrackingTitle: "ஆர்டர் கண்காணிப்பு",
    noOrdersText: "செயலில் உள்ள எந்த ஒரு ஆர்டரும் இல்லை",
    checkoutModalTitle: "செக் அவுட்",
    paymentMethodTitle: "கட்டண முறை",
    payNowLabel: "இப்போது கட்டணம் செலுத்து",
    buyNowPayLaterLabel: "இப்போது வாங்கி, பிறகு செலுத்தவும் (நியமிக்கப்பட்ட வாடிக்கையாளர்கள்)",
    transportServiceTitle: "போக்குவரத்து சேவை",
    needTransportLabel: "எனக்கு போக்குவரத்து சேவை தேவை",
    selectTransportOption: "போக்குவரத்து சேவையைத் தேர்ந்தெடு",
    cancelOrderBtn: "ரத்து செய்",
    confirmOrderBtn: "ஆர்டர் உறுதிப்படுத்துக",

    navbarBrandTransport: "போக்குவரத்து சேவை டாஷ்போர்ட்",
    slide1TitleTransport: "நம்பகமான போக்குவரத்து சேவைகள்",
    slide1DescTransport: "விற்பனையாளர்களை திறமையான விநியோக தீர்வுகளுடன் இணைத்து",
    slide2TitleTransport: "நேரடி கண்காணிப்பு",
    slide2DescTransport: "நேரடி GPS கண்காணிப்புடன் உங்கள் விநியோகங்களை கண்காணிக்கவும்",
    slide3TitleTransport: "வேகமாகவும் பாதுகாப்பான விநியோகம்",
    slide3DescTransport: "பொருட்களின் நேரத்திலும் பாதுகாப்பான விநியோகத்தை உறுதி செய்க",
    totalDeliveriesLabel: "மொத்த விநியோகங்கள்",
    totalEarningsLabel: "மொத்த சம்பாதிப்புகள்",
    activeRoutesLabel: "செயலில் உள்ள பாதைகள்",
    averageRatingLabel: "சராசரி மதிப்பீடு",
    deliveryRequestsTitle: "விநியோக கோரிக்கைகள்",
    requestStatusAll: "அனைத்து கோரிக்கைகளும்",
    requestStatusPending: "காத்திருக்கின்றன",
    requestStatusAccepted: "ஏற்றுக்கொள்ளப்பட்டது",
    requestStatusInTransit: "பயணத்தில் உள்ளது",
    requestStatusDelivered: "விநியோகம் செய்யப்பட்டவை",
    refreshMapBtn: "புதுப்பி",
    logoutBtnTransport: "வெளியேறு",
    requestDetailsTitle: "விநியோக கோரிக்கை விவரங்கள்",
    closeRequestDetailsBtn: "மூடு",
    rejectRequestBtn: "தவிர்க்கவும்",
    acceptRequestBtn: "கோரிக்கையை ஏற்கவும்",
    vehicleInfoTitle: "வாகனத் தகவல் புதுப்பிக்கவும்",
    cancelVehicleInfoBtn: "ரத்து செய்",
    saveVehicleInfoBtn: "தகவலை சேமி",
    vehicleTypeLabel: "வாகன வகை",
    selectTypeOption: "வகையைத் தேர்ந்தெடு",
    vehicleTypeBike: "பைக்",
    vehicleTypeAutoRickshaw: "ஆட்டோ ரிக்ஷா",
    vehicleTypeVan: "வான்",
    vehicleTypeTruck: "டிரக்",
    vehicleNumberLabel: "வாகன எண்",
    placeholderVehicleNumber: "வாகன எண் உள்ளிடவும்",
    capacityLabel: "திறன் (கிலோ)",
    placeholderCapacity: "திறனை உள்ளிடவும்",
    ratePerKmLabel: "கிமீக்கு விகிதம் (₹)",
    placeholderRatePerKm: "கிமீக்கு விகிதம் உள்ளிடவும்",
    serviceAreasLabel: "சேவை பகுதிகள்",
    placeholderServiceAreas: "நீங்கள் சேவை வழங்கும் பகுதிகளை உள்ளிடவும் (கோமா பிரிக்கப்பட்டவை)"
  }
};

// Language names mapping for display
const languageNames = {
  en: "English",
  hi: "हिंदी",
  ta: "தமிழ்"
};

function getCurrentLang() {
  return localStorage.getItem('selectedLanguage') || 'en';
}

function t(key) {
  const lang = getCurrentLang();
  return (window.translations && window.translations[lang] && window.translations[lang][key]) || key;
}

function updateLanguage(lang) {
  localStorage.setItem('selectedLanguage', lang);

  // Update text content
  document.querySelectorAll('[data-translate]').forEach(el => {
    const key = el.getAttribute('data-translate');
    el.textContent = t(key);
  });

  // Update placeholders
  document.querySelectorAll('[data-translate-placeholder]').forEach(el => {
    const key = el.getAttribute('data-translate-placeholder');
    el.placeholder = t(key);
  });
}

// Language selector logic

document.addEventListener('DOMContentLoaded', () => {
  // Set initial language
  const currentLang = getCurrentLang();
  updateLanguage(currentLang);

  // Set current language name in selector
  const langNames = {
    en: 'English',
    hi: 'हिंदी',
    ta: 'தமிழ்'
  };
  if (document.getElementById('currentLang')) {
    document.getElementById('currentLang').textContent = langNames[currentLang] || 'English';
  }

  // Dropdown toggle logic
  const btn = document.getElementById('languageBtn');
  const dropdown = document.getElementById('languageDropdown');
  if (btn && dropdown) {
    btn.addEventListener('click', (e) => {
      e.stopPropagation();
      dropdown.style.display = dropdown.style.display === 'block' ? 'none' : 'block';
    });
    // Hide dropdown when clicking outside
    document.addEventListener('click', (e) => {
      if (dropdown.style.display === 'block') {
        dropdown.style.display = 'none';
      }
    });
  }

  // Listen for language changes
  document.querySelectorAll('.language-option').forEach(option => {
    option.addEventListener('click', (e) => {
      e.stopPropagation();
      const lang = option.getAttribute('data-lang');
      updateLanguage(lang);
      if (document.getElementById('currentLang')) {
        document.getElementById('currentLang').textContent = langNames[lang] || option.textContent;
      }
      if (dropdown) dropdown.style.display = 'none';
    });
  });
});
